experiments:
  mcm5s2U_quantseq:
    STAR:
      --alignSJoverhangMin 999
      --outSJfilterOverhangMin -1 -1 -1 -1
      --outSJfilterReads Unique
      --outFilterMatchNminOverLread 0.3
      --outFilterMismatchNoverReadLmax 0.1
      --outFilterMismatchNmax 3
      --outFilterMultimapNmax 1
      --outSAMmapqUnique 60
      --outSAMattributes NH HI AS NM MD
      --outSAMtype BAM SortedByCoordinate
    flexbar:
      --pre-trim-left 24
      --adapter-preset TruSeq
      --max-uncalled 1
      --htrim-right ACGT
      --htrim-min-length 3
      --htrim-error-rate 0.25
      --min-read-length 12
      --length-dist
      --qtrim TAIL
      --qtrim-format sanger
      --qtrim-threshold 30
      --qtrim-post-removal
    gedi_grandslam:
      -no4sUpattern "_0IAA|_0h"
      -allGenes
      -full
      -introns
      -plot
      
        
